// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApCdA8jkHs8RaI4XsDAwSNi8Q48v-d1zI',
    appId: '1:28639589684:web:df877d5554d8e7d533a161',
    messagingSenderId: '28639589684',
    projectId: 'airline-system-4e527',
    authDomain: 'airline-system-4e527.firebaseapp.com',
    storageBucket: 'airline-system-4e527.appspot.com',
    measurementId: 'G-55BT1SNHMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnRrUq_TPtCzHwboWsCJlVUSEVcAwHo0o',
    appId: '1:28639589684:android:83f51a1972b036a833a161',
    messagingSenderId: '28639589684',
    projectId: 'airline-system-4e527',
    storageBucket: 'airline-system-4e527.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRCkxeXl25_AUhni1cQHz8TojtAruVO6Q',
    appId: '1:28639589684:ios:c416678f264cb43033a161',
    messagingSenderId: '28639589684',
    projectId: 'airline-system-4e527',
    storageBucket: 'airline-system-4e527.appspot.com',
    iosBundleId: 'com.travel.travelSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRCkxeXl25_AUhni1cQHz8TojtAruVO6Q',
    appId: '1:28639589684:ios:c416678f264cb43033a161',
    messagingSenderId: '28639589684',
    projectId: 'airline-system-4e527',
    storageBucket: 'airline-system-4e527.appspot.com',
    iosBundleId: 'com.travel.travelSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApCdA8jkHs8RaI4XsDAwSNi8Q48v-d1zI',
    appId: '1:28639589684:web:2f285dee868736ea33a161',
    messagingSenderId: '28639589684',
    projectId: 'airline-system-4e527',
    authDomain: 'airline-system-4e527.firebaseapp.com',
    storageBucket: 'airline-system-4e527.appspot.com',
    measurementId: 'G-XZME0MNGLY',
  );
}
